### ISSUE TITLE
Crash with pre-compiled screenshots

### ISSUE THREAD

**Issue by adilfazal** [Simbul/baker#258]
Hi ALL,
             I have about 60 pages magazine. And I am trying to use pre-compiled screenshots feature. But application crashes due to memory issue. 

Thanks,
Adil

**Comment by folletto** [comment]
Uhm that's weird. I guess we could optimimize that part of the code for sure, but first: did you try removing a few of them and see if there's a number around which reliably it crashes?

**Comment by adilfazal** [comment]
Hi Folletto, 
Yes, it works good with less pages. I have total 57 pages.

Thanks,

**Comment by Xm4s** [comment]
Hi adilfazal!

I may have provided a solution for the "page limit" problems, but of course I need your help to test it out :)

Since you seems to have a pretty long book could you please try the solution I've posted in #262 with your 50+ pages book? Maybe you can duplicate some pages to have something like 70-80 pages and see how it performs.

Thank you :)

**Comment by adilfazal** [comment]
Hi Marco,
              Thanks for quick update. I tried your solution it seems to me it have few issues. I experienced following issues.

1- Some of my html pages look different in this version. 
2- In landscape mode it shows different image and shows 1/3 of one screenshot and 2/3 of other screenshot.

Thanks,

**Comment by adilfazal** [comment]
Hi Marco,
              Actually, It have only one issue with landscape mode.
2- In landscape mode it shows different image and shows 1/3 of one screenshot and 2/3 of other screenshot.

Thanks,

**Comment by Xm4s** [comment]
Hi!

Ehm ... sorry for the landscape screenshots, my bad :P
Should be fixed with commit a11566bfd4dcddf4683ab7c8246437fd4d3d6afe

How many pages do you have in the book you are using for this test?

**Comment by adilfazal** [comment]
Thanks for reply, I have almost 70 images. Application still crashes after few minutes.

**Comment by folletto** [comment]
...what's in the log when it crashes? :)

**Comment by adilfazal** [comment]
Hi Marco,
              Application crashes after 50 pages mostly. Here is log detail.

Jan  3 11:15:42 unknown configd[25] <Notice>: jetsam: kernel memory event (95), free: 777, active: 1278, inactive: 737, purgeable: 193, wired: 13737
Jan  3 11:15:42 unknown cookerymag[923] <Warning>: Scrolling
Jan  3 11:15:42 unknown cookerymag[923] <Warning>: • User scroll
Jan  3 11:15:42 unknown cookerymag[923] <Warning>: • Hide status bar 
Jan  3 11:15:42 unknown cookerymag[923] <Warning>: • Scrollview will begin dragging
Jan  3 11:15:42 unknown cookerymag[923] <Warning>: • Hide status bar 
Jan  3 11:15:42 unknown cookerymag[923] <Warning>: • Scrollview did end dragging
Jan  3 11:15:42 unknown cookerymag[923] <Warning>: • Scrollview will begin decelerating
Jan  3 11:15:42 unknown cookerymag[923] <Warning>: • Swiping to page: 47
Jan  3 11:15:42 unknown cookerymag[923] <Warning>: • Goto page: book/19.html
Jan  3 11:15:42 unknown cookerymag[923] <Warning>: • Add page to the loding queue
Jan  3 11:15:42 unknown cookerymag[923] <Warning>: • Handle loading of slot 0 with page 47
Jan  3 11:15:42 unknown cookerymag[923] <Warning>: • Setup new page for loading
Jan  3 11:15:42 unknown cookerymag[923] <Warning>: • Setup webView
Jan  3 11:15:42 unknown cookerymag[923] <Warning>: • Loading: book/19.html
Jan  3 11:15:43 unknown com.apple.launchd[1] <Notice>: (UIKitApplication:com.Baker.cookerymag[0x1359]) Exited: Killed: 9
Jan  3 11:15:43 unknown configd[25] <Notice>: jetsam: kernel termination snapshot being created
Jan  3 11:15:43 unknown SpringBoard[29] <Warning>: Application 'Cookery 1' exited abnormally with signal 9: Killed: 9
Jan  3 11:15:44 unknown ReportCrash[925] <Error>: libMobileGestalt loadBasebandMobileEquipmentInfo: CommCenter error: 1:45
Jan  3 11:15:44 unknown ReportCrash[925] <Error>: libMobileGestalt copyInternationalMobileEquipmentIdentity: Could not get mobile equipment info dictionary
Jan  3 11:15:44 unknown ReportCrash[925] <Error>: Saved crashreport to /Library/Logs/CrashReporter/LowMemory-2012-01-03-111544.plist using uid: 0 gid: 0, synthetic_euid: 0 egid: 0

**Comment by folletto** [comment]
Now the screenshots are handled better, we introduced some complexity but it should avoid crashes for screenshot mode plus big books. Kudos to @Xm4s.

There are two internal variables added with Commit 8a30fc6bff5e4dd3db68d774fc2ec854a4fc68e9.

```
// SCREENSHOT
#define MAX_SCREENSHOT_AFTER_CP  10
#define MAX_SCREENSHOT_BEFORE_CP 10
```

This allows to change the number of screenshots pre-loaded. If you swipe very quickly _more_ than this number, the usual spinner appears.

We might have to finetune the two numbers above to avoid crashes, but, overall, this works. Issue closed. :)
