### ISSUE TITLE
Baker does not recognize orientation parameters

### ISSUE THREAD

**Issue by tstegart** [Simbul/baker#552]
I have set the app up to only be used in portrait mode but the Baker shelf view rotates to both portrait and landscape. My downloaded issues also open up in both portrait and landscape, even though this is explicitly set to portrait only in the book.json file. So Baker is ignoring something somewhere.

**Comment by folletto** [comment]
Thanks. ;)

I think it's going to be more complex than that, because the shelf is independent from the book, but we can look into it. There might be already a solution, but I prefer to have a separate issue so we can address this properly. ;)

**Comment by tstegart** [comment]
It could have something to do with this: http://dhilipsiva.blogspot.com/2012/07/ios-6-ui-interface-orientation.html

**Comment by folletto** [comment]
Did you maybe try to disable the other orientation in the app configuration? 
_(See the first screenshot [here](http://cubiq.org/build-and-publish-an-html5-game-for-ipad-part-2))_

**Comment by tstegart** [comment]
Yes. I'm pretty sure I've found all the ways I can see to limit the orientation, but maybe I still have something wrong. Can anyone else get it limited to portrait?

**Comment by anjimi** [comment]
I'm actually having the opposite problem, but could be related...
My app which is set up for both portrait and landscape, has always worked in both orientations until I updated from Xcode 4.3.2 to 4.5.2 recently. Only loads portrait in iOS 6, on both iPad and iPhone simulators, and on an actual iPhone with iOS 6. Still works fine portrait and landscape in iOS 5.1.

Note, this is using Baker 3.2, I've not got to testing the shelf yet, hopefully soon!

**Comment by folletto** [comment]
I ask you to test the shelf then, it might be already fixed there. ;)

**Comment by tstegart** [comment]
Has anyone else run across this or found a solution? Its one of the things holding us back from submitting to Apple because all of our issues are only designed for portrait. I can't have it switch to landscape.

**Comment by anjimi** [comment]
For the record, my app is working fine both portrait and landscape with Baker 4.0 in iOS 6. :)

**Comment by Xm4s** [comment]
I fixed the orientation recognition with commit 46e46c3f125d7d379f92c7acd267218bdc11e408
Now the orientation param specified in book.json is handled correctly and the book will support only the orientation specified.

NB: while I was working on the bug I also noticed that iOS 5.1 simulator seems to ignore the supported orientation param specified in the Xcode project settings, while iOS 6.0 works as expected.

**Comment by tstegart** [comment]
Can we reopen this? I believe it is still a bug. My iPad 1 running iOS 5.1.1 still does not recognize orientation parameters, both the ones set in the json file and the ones set in Xcode. 

iOS 6 seems to be fixed though (thanks @Xm4s!).

**Comment by tstegart** [comment]
Since the commit by @Xm4s above, Baker now recognizes my orientation parameters on iOS 5 inside the issues of my magazine. Its only the shelf that does not recognize the parameters. So I'm guessing the problem is that the shelf view controller doesn't seem to have any code limiting which orientations are supported. It seems to recognize them all. 

I think it may be related to this part of the iOS guidelines:
"On iOS 5 and earlier, a view controller can sometimes participate in the rotation process even when it isn’t the topmost full-screen view controller. This generally occurs when a container view controller asks its children for their supported interface orientations. In practice, the ability for children to override the parents is rarely useful."
http://developer.apple.com/library/ios/#featuredarticles/ViewControllerPGforiPhoneOS/RespondingtoDeviceOrientationChanges/RespondingtoDeviceOrientationChanges.html

**Comment by folletto** [comment]
We are aware of that, it's a bug on Apple's side. See the "NB" that @Xm4s wrote above:

> NB: while I was working on the bug I also noticed that iOS 5.1 simulator seems to ignore the supported orientation param specified in the Xcode project settings, while iOS 6.0 works as expected.

You might try to fill a bug report on Apple's side, or try to solve it yourself - who knows, maybe we missed something.

**Comment by f3r3nc** [comment]
The rotation handling between iOS5 and iOS6 has been changed. 
When selecting the supported orientation in XCode, it basically changes the Info.plist. 
The values there are only used in iOS6. For previous iOS versions the supported orientations needs to set programmatically.

In the fix above https://github.com/Simbul/baker/commit/46e46c3f125d7d379f92c7acd267218bdc11e408,  [shouldAutorotateToInterfaceOrientation:](https://github.com/Simbul/baker/blob/46e46c3f125d7d379f92c7acd267218bdc11e408/BakerShelf/ShelfViewController.m#L154) returns YES thus all device orientations will be supported.

I'd suggest to change the method shouldAutorotateToInterfaceOrientation: in ShelfViewController.m so that in consults the Info.plist to return the appropriate value. As BakerViewController sets this according to the orientation value defined in the Hpub it seems to be the only place to make this change.

I can send this in a pull request if there no other views need to be adjusted.

**Comment by tstegart** [comment]
I asked someone to take a look at this and he came up with a stopgap solution for anyone who needs to force Baker to accept portrait orientation in iOS 5 and 6. The code is as follows:

Add this to the end of UICustomNavigationController.m

```
- (BOOL)shouldAutorotateToInterfaceOrientation:(UIInterfaceOrientation)interfaceOrientation
{
return UIInterfaceOrientationIsPortrait(interfaceOrientation);
} 
```

He is working on a general Baker solution for both orientations, but I'm not sure if he will find one. Hopefully this will help people out until iOS 5 is no longer widely used.

**Comment by folletto** [comment]
Wait, it's not that simple, because the orientation depends also on what the single book declares. So you have to blend both the in-app orientation setting and the `book.json` orientation setting.

I'll probably leave this thread to @Xm4s to comment since afaik he's the one that implemented that part.

**Comment by tstegart** [comment]
EDIT - I think our comments got out of order, who were you replying to @folletto? 
All our books use portrait as the orientation in every book.json file. This is just a stop-gap solution for people who need their app to only use portrait everywhere. It seems to work in testing fine. It won't work for people who need to switch orientations.

**Comment by Xm4s** [comment]
@f3r3nc you are right, it seems that the only way to make the "supported orientation" flag works in iOS 5 is to read the info.plist and return YES in _shouldAutorotateToInterfaceOrientation_ only for the supported orientation.

Another possible solution is to add a configuration parameter, similar to the one in the _book.json_, to define the orientations supported by the shelf (thus avoiding the info.plist completely).

We're deciding what course of action is the best, wait for the fix soon :)

**Comment by f3r3nc** [comment]
@Xm4s 
If you are thinking about a more general solution (ie: other platforms) you will need to extend the books.json with an orientation parameter. Although, as it's an array at the moment, it will break compatibility.

If the solution is aiming iOS only, I would suggest relying on Info.plist since iOS6 is expecting that value there and so its offers a nice way to support backward compatibility.

**Comment by folletto** [comment]
`book.json` already has `orientation`. ;)

But as said above, it's a combination of that and another parameter (shelf.json? plist? other?) for the shelf. We are still not sure about it. :)

On top of that, consider also that iOS5 will disappear soon enough, so we're not sure if it's time well spent overall. :)

**Comment by f3r3nc** [comment]
yeah I can see that for the book, but when used for the shelf (NEWSSTAND_MANIFEST_URL) it becomes an array and so nothing describes how the shelf itself should be presented just the individual issues :)

**Comment by folletto** [comment]
Yep, but that's easily changed... however I don't want to give too much weight that option, it's on par of others.  

Overall however, the main point is the one raised above: it's an Apple "bug" and at the same time iOS6 was already over 60% of market share in october 2012, so...

**Comment by f3r3nc** [comment]
well okay :)
here is a snippet worth looking at for solving this issue:
https://gist.github.com/2853792

**Comment by Xm4s** [comment]
Thanks for the snippet @f3r3nc, with the commit 9c3f867a the iOS 5 orientation bug should be resolved

**Comment by f3r3nc** [comment]
glad it worked out. :)
